# Generated by Django 3.0.4 on 2020-05-09 23:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category Name', max_length=50)),
                ('subcategory_name', models.CharField(help_text='SubCategory Name', max_length=50)),
                ('subcategory_description', models.TextField(default='-', help_text='SubCategory Description')),
                ('subcategory_date', models.DateTimeField(default=datetime.datetime.now, help_text='SubCategory Date Created')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Slug', populate_from='subcategory_name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Categories')),
            ],
            options={
                'ordering': ['subcategory_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubCategories',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category Name', max_length=50)),
                ('subcategory_name', models.CharField(help_text='SubCategory Name', max_length=50)),
                ('subcategory_description', models.TextField(default='-', help_text='SubCategory Description')),
                ('subcategory_date', models.DateTimeField(default=datetime.datetime.now, help_text='SubCategory Date Created')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Slug', populate_from='subcategory_name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='categories.Categories')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sub categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
