# Generated by Django 3.0.4 on 2020-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(help_text='Category ID')),
                ('category_name', models.CharField(help_text='Category Name', max_length=50)),
                ('subcategory_name', models.CharField(help_text='SubCategory Name', max_length=50)),
                ('subcategory_description', models.TextField(default='-', help_text='SubCategory Description')),
            ],
        ),
    ]
