# Generated by Django 3.0.4 on 2020-04-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='category_id',
        ),
    ]
