# Generated by Django 3.0.4 on 2020-04-24 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0002_remove_subcategories_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.DateField(default=datetime.datetime.now, help_text='SubCategory Date Created'),
        ),
    ]
