# Generated by Django 3.0.5 on 2020-05-04 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0003_subcategories_subcategory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='SubCategory Date Created'),
        ),
    ]
