# Generated by Django 3.0.5 on 2020-05-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0004_auto_20200504_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.CharField(default='05/04/2020 | 00:09:28 AM', help_text='SubCategory Date Created', max_length=50),
        ),
    ]
