# Generated by Django 3.0.5 on 2020-05-05 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0005_auto_20200504_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 0, 41, 22, 996447), help_text='SubCategory Date Created'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.CharField(default='05/04/2020 | 20:41:22 PM', help_text='SubCategory Date Created', max_length=50),
        ),
    ]
