# Generated by Django 3.0.5 on 2020-05-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0007_auto_20200505_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.DateTimeField(default='2020-05-05 01:04', help_text='SubCategory Date Created'),
        ),
    ]
