# Generated by Django 3.0.5 on 2020-05-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0008_auto_20200505_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='subcategory_date1',
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.DateTimeField(default='2020-05-04 22:02', help_text='SubCategory Date Created'),
        ),
    ]
