# Generated by Django 3.0.5 on 2020-05-05 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0009_auto_20200504_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='SubCategory Date Created'),
        ),
    ]
