# Generated by Django 3.0.4 on 2020-05-06 01:55

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0010_auto_20200504_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='category_name'),
        ),
    ]
