# Generated by Django 3.0.4 on 2020-05-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0011_subcategories_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
