# Generated by Django 3.0.4 on 2020-05-06 02:00

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0012_auto_20200505_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Slug', populate_from='category_name'),
        ),
    ]
