# Generated by Django 3.0.4 on 2020-05-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0013_auto_20200505_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
