# Generated by Django 3.0.4 on 2020-05-07 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categories_slug'),
        ('subcategories', '0015_auto_20200507_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ['subcategory_name']},
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='categories.Categories'),
            preserve_default=False,
        ),
    ]
