# Generated by Django 3.0.4 on 2020-05-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(help_text='Article Name', max_length=50)),
                ('article_short', models.TextField()),
                ('article_body', models.TextField()),
                ('article_date', models.CharField(help_text='Article Date', max_length=50)),
                ('article_picture_name', models.TextField()),
                ('article_picture_url', models.TextField(default='-')),
                ('article_author', models.CharField(help_text='Article Author', max_length=50)),
                ('article_category_id', models.IntegerField(default=0)),
                ('article_views', models.IntegerField(default=0)),
                ('article_status', models.CharField(default='-', max_length=30)),
                ('article_percentage', models.IntegerField(default=0)),
                ('article_live', models.BooleanField(default='False', help_text='Article Live Switch')),
                ('article_date_readable', models.CharField(default='-', max_length=50)),
                ('article_category', models.CharField(default='-', max_length=50)),
                ('article_subcategory', models.CharField(default='-', max_length=50)),
                ('article_image_size', models.CharField(default='-', max_length=20)),
            ],
        ),
    ]
