# Generated by Django 3.0.5 on 2020-05-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='article_category_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='article_date_readable',
        ),
        migrations.AddField(
            model_name='news',
            name='article_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Article Date Created'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Slug', populate_from='article_name'),
        ),
        migrations.CreateModel(
            name='HistoricalNews',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('article_name', models.CharField(help_text='Article Name', max_length=50)),
                ('article_short', models.TextField()),
                ('article_body', models.TextField()),
                ('article_date', models.CharField(help_text='Article Date', max_length=50)),
                ('article_picture_name', models.TextField()),
                ('article_picture_url', models.TextField(default='-')),
                ('article_author', models.CharField(help_text='Article Author', max_length=50)),
                ('article_views', models.IntegerField(default=0)),
                ('article_status', models.CharField(default='-', max_length=30)),
                ('article_percentage', models.IntegerField(default=0)),
                ('article_live', models.BooleanField(default='False', help_text='Article Live Switch')),
                ('article_date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Article Date Created')),
                ('article_category', models.CharField(default='-', max_length=50)),
                ('article_subcategory', models.CharField(default='-', max_length=50)),
                ('article_image_size', models.CharField(default='-', max_length=20)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Slug', populate_from='article_name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical news',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
