# Generated by Django 3.0.4 on 2020-05-10 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_date',
            field=models.DateField(default=datetime.datetime.now, help_text='Category Date Created'),
        ),
        migrations.AlterField(
            model_name='historicalcategories',
            name='category_date',
            field=models.DateField(default=datetime.datetime.now, help_text='Category Date Created'),
        ),
    ]
