# Generated by Django 3.0.5 on 2020-05-12 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Category Date Created'),
        ),
        migrations.AlterField(
            model_name='historicalcategories',
            name='category_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Category Date Created'),
        ),
    ]
