# Generated by Django 3.0.4 on 2020-05-10 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200509_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_date_human',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Category Date Created'),
        ),
        migrations.AddField(
            model_name='historicalcategories',
            name='category_date_human',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Category Date Created'),
        ),
    ]
