# Generated by Django 3.0.4 on 2020-05-10 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200509_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 0, 44, 21, 628229, tzinfo=utc), help_text='Category Date Created'),
        ),
        migrations.AlterField(
            model_name='historicalcategories',
            name='category_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 0, 44, 21, 628229, tzinfo=utc), help_text='Category Date Created'),
        ),
    ]
