# Generated by Django 3.0.4 on 2020-05-10 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200509_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Category Date Created'),
        ),
        migrations.AlterField(
            model_name='historicalcategories',
            name='category_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Category Date Created'),
        ),
    ]
